steps:
- id: texlive
  name: 'gcr.io/overleaf-ops/texlive-full:2017.1'
- id: build
  name: 'gcr.io/overleaf-ops/cloud-builder'
  args: 
  - 'build'
  env:
  - 'BUILD_NUMBER=$SHORT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
  waitFor: ['-']
- id: test_unit
  name: 'gcr.io/overleaf-ops/cloud-builder'
  args: 
  - 'test_unit'
  env:
  - 'DOCKER_COMPOSE_FLAGS=-f docker-compose.ci.yml'
  - 'BUILD_NUMBER=$SHORT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
  waitFor:
  - build
- id: test_acceptance
  name: 'gcr.io/overleaf-ops/cloud-builder'
  args: 
  - 'test_acceptance'
  env:
  - 'DOCKER_COMPOSE_FLAGS=-f docker-compose.ci.yml'
  - 'BUILD_NUMBER=$SHORT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TEXLIVE_IMAGE=gcr.io/overleaf-ops/texlive-full:2017.1'
  waitFor:
  - build
  - texlive
images:
  - 'gcr.io/$PROJECT_ID/clsi:${BRANCH_NAME}-${SHORT_SHA}'
timeout: 1800s
options:
  diskSizeGb: 200
  machineType: 'N1_HIGHCPU_8'
