steps:
- name: 'gcr.io/overleaf-ops/texlive-full:2018.1.002'
- name: 'gcr.io/overleaf-ops/cloud-builder'
  args: 
  - 'build'
  env:
  - 'BUILD_NUMBER=$SHORT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
- name: 'gcr.io/overleaf-ops/cloud-builder'
  args: 
  - 'test_unit'
  env:
  - 'DOCKER_COMPOSE_FLAGS=-f docker-compose.ci.yml'
  - 'BUILD_NUMBER=$SHORT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
- name: 'gcr.io/overleaf-ops/cloud-builder'
  args: 
  - 'test_acceptance'
  env:
  - 'DOCKER_COMPOSE_FLAGS=-f docker-compose.ci.yml'
  - 'BUILD_NUMBER=$SHORT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TEXLIVE_IMAGE=gcr.io/overleaf-ops/texlive-full:2018.1.002'
images:
  - 'gcr.io/$PROJECT_ID/clsi:${BRANCH_NAME}-${SHORT_SHA}'
